// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs1KTABMWOPna-wwQQ5IF52qGbQ_qBxbw',
    appId: '1:963790521039:web:72bf9bbaa8e29f562f6dba',
    messagingSenderId: '963790521039',
    projectId: 'shopee-app-9a04d',
    authDomain: 'shopee-app-9a04d.firebaseapp.com',
    storageBucket: 'shopee-app-9a04d.firebasestorage.app',
    measurementId: 'G-P2LZ8EJJTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnDLCr7IO_tLt564_rwYjbXzG4-XdllEc',
    appId: '1:963790521039:android:4e78cbc70ce2b0442f6dba',
    messagingSenderId: '963790521039',
    projectId: 'shopee-app-9a04d',
    storageBucket: 'shopee-app-9a04d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSg822hOVJpLU3RP51z4oftouG7cdR3N0',
    appId: '1:963790521039:ios:d00688c7f2d1d01a2f6dba',
    messagingSenderId: '963790521039',
    projectId: 'shopee-app-9a04d',
    storageBucket: 'shopee-app-9a04d.firebasestorage.app',
    iosBundleId: 'com.example.shoppeApp',
  );
}
